server:
  port: 8080

spring:
  profiles:
    include:
      - domain
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: fintech
      auto-offset-reset: earliest
  output:
    ansi:
      enabled: always
